# Docker compose file for Thumbs - YouTube thumbnail proxy

services:
  Thumbs:
    build: .
    image: ghcr.io/javadalmasi/thumbs:latest
    container_name: Thumbs
    restart: unless-stopped
    ports:
      - "8080:8080/tcp" # HTTP
    environment:
      - SECRET_KEY=1234567890123456  # Environment variable for 16-character secret key
      - YTPROXY_PORT=8080
    # Needed for HTTP/3, otherwise, quic-go will output this depending of the machine:
    # "failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). 
    # See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."
    cap_add:
      - NET_ADMIN
    networks:
      - thumbs_network

  # You can comment this whole service if you are not going to use Gluetun at all
  gluetun:
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    ports:
      # THIS IS ACTUALLY THE PORT OF THUMBS
      # SINCE THE THUMBS SERVICE IS RUNNING
      # UNDER GLUETUN NETWORK.
      - "8443:8443/tcp" # HTTP/2
      - "8443:8443/udp" # HTTP/3 (QUIC)
    environment:
      - HTTPPROXY_ENABLED=true
      - HTTPPROXY_PORT=8888
      - VPN_TYPE=wireguard  # or openvpn
      # Add other VPN provider specific settings
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    networks:
      - thumbs_network

networks:
  thumbs_network:
    driver: bridge
