# Docker compose file for http3-ytproxy used in inv.nadeko.net

services:
  http3-proxy:
    build: .
    image: git.nadeko.net/fijxu/http3-ytproxy:latest
    restart: always
    # Uncomment this IF YOU ARE using gluetun!
    # network_mode: "service:gluetun"
    # Uncomment this IF YOU ARE NOT using gluetun!
    # ports:
    #   - "0.0.0.0:8443:8443/tcp" # HTTP/2
    #   - "0.0.0.0:8443:8443/udp" # HTTP/3 (QUIC)
    # Make sure that the key and the certificate files exist!
    volumes:
      - ./key.key:/data/key.key:ro
      - ./fullchain.pem:/data/cert.pem:ro
    depends_on:
      gluetun:
        condition: service_healthy
    # Needed for HTTP/3, otherwise, quic-go will output this depending of the machine:
    # "failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). 
    # See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."
    cap_add:
      - NET_ADMIN

  # You can comment this whole service if you are not going to use Gluetun at all
  gluetun:
    image: qmcgaw/gluetun:latest
    restart: always
    ports:
      # THIS IS ACTUALLY THE PORT OF HTTP3-PROXY
      # SINCE THE HTTP3-PTOXY SERVICE IS RUNNING
      # UNDER GLUETUN NETWORK.
      - "0.0.0.0:8443:8443/tcp" # HTTP/2
      - "0.0.0.0:8443:8443/udp" # HTTP/3 (QUIC)
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
