name: "CI"

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Docker BuildX system
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Container Registry (git.nadeko.net)
        uses: docker/login-action@v3
        with:
          registry: git.nadeko.net
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: git.nadeko.net/fijxu/http3-ytproxy
          tags: |
            type=sha,format=short,prefix={{date 'YYYY.MM.DD'}}-,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
